# Generated by Django 4.1.2 on 2022-10-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название места')),
                ('description_short', models.TextField(verbose_name='Краткое описание места')),
                ('description_long', models.TextField(verbose_name='Развернутое описание места')),
                ('lat', models.FloatField(verbose_name='Широта в местоположении')),
                ('lng', models.FloatField(verbose_name='Долгота в местоположении')),
            ],
        ),
    ]
