# Generated by Django 4.1.2 on 2022-10-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimage',
            name='position',
            field=models.PositiveIntegerField(null=True, verbose_name='Позиция фото для места'),
        ),
    ]
