# Generated by Django 4.1.2 on 2022-10-13 14:56

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_placeimage_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='place',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
