# Generated by Django 4.1.2 on 2022-10-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_description_long_alter_place_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='test_description',
            field=models.TextField(blank=True),
        ),
    ]
