# Generated by Django 4.1.2 on 2022-10-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_place_test_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placeimage',
            unique_together={('place', 'image')},
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('title', 'lat'), name='name of constraint'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('title', 'lng'), name='name of secound constraint'),
        ),
    ]
