# Generated by Django 4.1.2 on 2022-10-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_placeimage_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='place',
            name='name of constraint',
        ),
        migrations.RemoveConstraint(
            model_name='place',
            name='name of secound constraint',
        ),
        migrations.RemoveField(
            model_name='place',
            name='test_description',
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('title', 'lat'), name='title and latitude'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('title', 'lng'), name='title and longitude'),
        ),
    ]
