# Generated by Django 4.1.2 on 2022-10-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_remove_place_title and latitude_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaceImage',
            new_name='Image',
        ),
    ]
